# Generated by Django 6.1.1 on 2026-10-01 16:29

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, unique=True)),
                ('path', models.CharField(help_text='Relative to MEDIA_ROOT, e.g. tts/<sha1>.wav.', max_length=255)),
                ('voice', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_pool_cap', models.PositiveSmallIntegerField(default=5)),
                ('accuracy_threshold', models.FloatField(default=0.85)),
                ('accuracy_window', models.PositiveSmallIntegerField(default=20)),
                ('session_correct_required', models.PositiveSmallIntegerField(default=3)),
                ('consolidation_gaps', models.JSONField(default=main.models.default_consolidation_gaps, help_text='Gaps in days.')),
                ('target_retention', models.FloatField(default=0.9)),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setswana', models.CharField(help_text='Headword in modern spelling.', max_length=200)),
                ('english', models.TextField(blank=True)),
                ('pos', models.CharField(blank=True, help_text='Part of speech, e.g. n, v, adj.', max_length=20)),
                ('noun_class', models.CharField(blank=True, max_length=10)),
                ('plural', models.CharField(blank=True, max_length=200)),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, db_index=True, help_text='Learning order; null = unscheduled.', null=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('rank', 'setswana'),
                'constraints': [models.UniqueConstraint(fields=('setswana', 'pos'), name='unique_lexeme_setswana_pos')],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('en_to_tn', 'English → Setswana'), ('audio_to_tn', 'Audio → Setswana')], default='en_to_tn', max_length=20)),
                ('stage', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('consolidating', 'Consolidating'), ('long_term', 'Long-term')], db_index=True, default='new', max_length=20)),
                ('consolidation_step', models.PositiveSmallIntegerField(default=0)),
                ('session_correct', models.PositiveSmallIntegerField(default=0)),
                ('due', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('stability', models.FloatField(blank=True, null=True)),
                ('difficulty', models.FloatField(blank=True, null=True)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('introduced_at', models.DateTimeField(blank=True, null=True)),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main.lexeme')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed', models.CharField(blank=True, max_length=200)),
                ('correct', models.BooleanField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.card')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('lexeme', 'direction'), name='unique_card_lexeme_direction'),
        ),
    ]
