# Generated by Django 6.1.1 on 2026-10-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexeme',
            name='curated_order',
            field=models.PositiveIntegerField(blank=True, help_text='Position in the curated Peace Corps list; ranked first.', null=True),
        ),
    ]
